# Generated by Django 3.2 on 2021-09-02 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_useranswer_user_quiz_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answers_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
